[package]
name = "flunk_website"
version = "0.1.0"
edition = "2021"
description = "Frontend for Flunk Website"
readme = "README.md"
repository = "https://github.com/LukeBrandon/fluke"
license = "MIT OR Apache-2.0"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

[dependencies]
yew = { version="0.20", features=["csr"] }
yew-router = "0.15.0"
log = "0.4"
wasm-logger = "0.2"
