version: '3'
services:
  local-db:
    image: postgres:latest
    env_file: .env
    ports:
      - 5432:5432
  backend:
    image: fluke-backend:dev
    depends_on:
      - local-db
    ports:
      - 8000:8000
