
name: Cargo build and test

on:
  pull_request:
    branches: [ master ]

env:
    SQLX_OFFLINE: true

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: backend build
      working-directory: ./backend
      run: cargo build --verbose

  docker-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build backend docker image
      run: |
        cd backend
        docker build -t fluke-backend:dev .

    - name: Setup and start services
      run: docker-compose up -d

    - name: Initialize database
      uses: jakejarvis/wait-action@master
      with:
        time: '30s'

    - name: Docker-based test
      run: |
        cd backend
        docker exec backend cargo test
